"""create base tables

Revision ID: 1030833f5fad
Revises: 
Create Date: 2025-11-29 00:36:06.612158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1030833f5fad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparation_stage_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('annual_volume_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('week_volume_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('speed_training_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tempo_training_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interval_training_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('distance_training_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('strength_training_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preparation_stage_configuration')),
    comment='Конфигурация этапа подготовки'
    )
    op.create_table('training_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('planned_annual_volume', sa.Integer(), nullable=False),
    sa.Column('actual_annual_volume', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plan')),
    comment='План тренировок'
    )
    op.create_table('training_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intensity', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_type')),
    comment='Тип тренировки'
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    comment='Таблица пользователей'
    )
    op.create_table('weekly_scheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monday_load', sa.String(), nullable=False),
    sa.Column('tuesday_load', sa.String(), nullable=False),
    sa.Column('wednesday_load', sa.String(), nullable=False),
    sa.Column('thursday_load', sa.String(), nullable=False),
    sa.Column('friday_load', sa.String(), nullable=False),
    sa.Column('saturday_load', sa.String(), nullable=False),
    sa.Column('sunday_load', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_scheme')),
    comment='Недельная схема'
    )
    op.create_table('preparation_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cycle_volume', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('week_volume', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('planned_speed_training_volume', sa.Integer(), nullable=False),
    sa.Column('actual_speed_training_volume', sa.Integer(), nullable=False),
    sa.Column('planned_tempo_training_volume', sa.Integer(), nullable=False),
    sa.Column('actual_tempo_training_volume', sa.Integer(), nullable=False),
    sa.Column('planned_interval_training_volume', sa.Integer(), nullable=False),
    sa.Column('actual_interval_training_volume', sa.Integer(), nullable=False),
    sa.Column('planned_distance_training_volume', sa.Integer(), nullable=False),
    sa.Column('actual_distance_training_volume', sa.Integer(), nullable=False),
    sa.Column('planned_strength_training_volume', sa.Integer(), nullable=False),
    sa.Column('actual_strength_training_volume', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('preparation_stage_configuration_id', sa.Integer(), nullable=False),
    sa.Column('weekly_scheme_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['preparation_stage_configuration_id'], ['preparation_stage_configuration.id'], name=op.f('fk_preparation_stage_preparation_stage_configuration_id_preparation_stage_configuration')),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plan.id'], name=op.f('fk_preparation_stage_training_plan_id_training_plan')),
    sa.ForeignKeyConstraint(['weekly_scheme_id'], ['weekly_scheme.id'], name=op.f('fk_preparation_stage_weekly_scheme_id_weekly_scheme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preparation_stage')),
    comment='Этап подготовки'
    )
    op.create_table('user_friends',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name=op.f('fk_user_friends_friend_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_friends_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name=op.f('pk_user_friends')),
    comment='Таблица друзей пользователя, связи пользователей с другими пользователями'
    )
    op.create_table('user_training_plan',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plan.id'], name=op.f('fk_user_training_plan_training_plan_id_training_plan')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_training_plan_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'training_plan_id', name=op.f('pk_user_training_plan')),
    comment='Таблица планов тренировок пользователя, связи пользователей с их планами тренировками'
    )
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('training_type_id', sa.Integer(), nullable=False),
    sa.Column('planned_duration_training', sa.Interval(), nullable=False),
    sa.Column('actual_duration_training', sa.Interval(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rpe_scale', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('covered_distance', sa.Integer(), nullable=False),
    sa.Column('preparation_stage_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['preparation_stage_id'], ['preparation_stage.id'], name=op.f('fk_training_preparation_stage_id_preparation_stage')),
    sa.ForeignKeyConstraint(['training_type_id'], ['training_type.id'], name=op.f('fk_training_training_type_id_training_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training')),
    comment='Тренировка'
    )
    op.create_table('training_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('training_zone', postgresql.INT4RANGE(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], name=op.f('fk_training_block_training_id_training')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_block')),
    comment='Тренировочный блок'
    )
    op.create_table('user_training',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], name=op.f('fk_user_training_training_id_training')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_training_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'training_id', name=op.f('pk_user_training')),
    comment='Таблица тренировок пользователя, связи пользователей с их тренировками'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_training')
    op.drop_table('training_block')
    op.drop_table('training')
    op.drop_table('user_training_plan')
    op.drop_table('user_friends')
    op.drop_table('preparation_stage')
    op.drop_table('weekly_scheme')
    op.drop_table('user')
    op.drop_table('training_type')
    op.drop_table('training_plan')
    op.drop_table('preparation_stage_configuration')
    # ### end Alembic commands ###
