"""make preparation_stage_id temporary nullable for training

Revision ID: 441426231a28
Revises: 1030833f5fad
Create Date: 2025-12-19 19:54:36.313071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '441426231a28'
down_revision: Union[str, Sequence[str], None] = '1030833f5fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training', 'actual_duration_training',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('training', 'rpe_scale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('training', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('training', 'covered_distance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('training', 'preparation_stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training', 'preparation_stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training', 'covered_distance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('training', 'rpe_scale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training', 'actual_duration_training',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    # ### end Alembic commands ###
